"""Discord delivery only: durable, bounded retries; never executes workout actions."""
from __future__ import annotations
import asyncio
import hashlib
import math
import json
import os
import random
import re
import time
import uuid
from pathlib import Path
from .discord_bot import render_bot
from .notification_context import notification_kind, health_notice
from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode
import aiohttp
import aiosqlite

CHANNELS = ('telegram', 'ha', 'discord')


class DiscordDeliveryError(RuntimeError):
    """Failure already recorded by the durable delivery worker."""


def webhook_url(value: str) -> str:
    p = urlsplit(value.strip())
    if (p.scheme != 'https' or p.hostname not in ('discord.com', 'canary.discord.com', 'ptb.discord.com')
            or p.username or p.password or p.port not in (None, 443)
            or p.fragment or not re.fullmatch(r'/api(?:/v\d+)?/webhooks/\d+/[A-Za-z0-9._-]+', p.path)):
        raise ValueError('כתובת Discord Webhook אינה תקינה')
    return urlunsplit((p.scheme, p.netloc, p.path, urlencode(dict(parse_qsl(p.query), wait='true')), ''))


def render(text, buttons, app_url):
    # Plain shared text is escaped independently of Telegram formatting.
    escaped = re.sub(r'([\\`*_~|>\[\]#])', r'\\\1', text)
    escaped = escaped.replace('@', '@\u200b')
    links = []
    for row in buttons or []:
        for b in row:
            url = b.get('uri') or b.get('url')
            if url and urlsplit(url).scheme in ('http', 'https') and url not in links:
                links.append(url)
    if app_url and app_url not in links:
        links.append(app_url.rstrip('/') + '/mine')
    # URI buttons are already generated by the application. No callback is a URL.
    if links:
        escaped += '\n\n' + '\n'.join('פתיחה: <'+u.replace('>', '%3E').replace('<','%3C')+'>' for u in links)
    parts=[]
    while escaped:
        cut=0; units=0
        for char in escaped:
            size=2 if ord(char)>0xffff else 1
            if units+size>1800: break
            units+=size; cut+=1
        if cut<len(escaped):
            newline=escaped.rfind('\n',0,cut)
            if newline>cut//2:cut=newline+1
            # Do not split an escaping backslash from the following character.
            while cut>1 and escaped[cut-1]=='\\':cut-=1
        parts.append({'content':escaped[:cut], 'allowed_mentions':{'parse':[]}})
        escaped=escaped[cut:]
    return parts or [{'content':'Arbox Companion', 'allowed_mentions':{'parse':[]}}]


class DiscordDelivery:
    def __init__(self, settings, log):
        self.settings=settings; self.log=log
        self.path=Path(settings._path).parent/'discord-delivery.db'
        self.db=None; self.task=None; self.lock=asyncio.Lock(); self.http=None
        self.audit = None

    async def start(self):
        async with self.lock:
            if self.db:return
            self.db=await aiosqlite.connect(self.path)
            os.chmod(self.path,0o600)
            self.db.row_factory=aiosqlite.Row
            await self.db.execute('''CREATE TABLE IF NOT EXISTS delivery (
                event_id TEXT, destination TEXT, part INTEGER, payload TEXT,
                created REAL, state TEXT, attempts INTEGER DEFAULT 0, next_attempt REAL,
                message_id TEXT, error TEXT, PRIMARY KEY(event_id,destination,part))''')
            columns = {r[1] for r in await (await self.db.execute('PRAGMA table_info(delivery)')).fetchall()}
            for name, definition in (('kind', "TEXT DEFAULT 'system'"), ('target', "TEXT DEFAULT 'primary'"), ('health_notice', 'INTEGER DEFAULT 0')):
                if name not in columns:
                    await self.db.execute(f'ALTER TABLE delivery ADD COLUMN {name} {definition}')
            # A process may have died after Discord accepted a request.
            await self.db.execute("UPDATE delivery SET state='unknown',error='interrupted' WHERE state='sending'")
            await self.db.execute("DELETE FROM delivery WHERE created<? AND state IN ('sent','failed','unknown')",(time.time()-30*86400,))
            await self.db.commit()
        self.task=asyncio.create_task(self.worker())

    async def close(self):
        if self.task:
            self.task.cancel()
            await asyncio.gather(self.task,return_exceptions=True)
        if self.http:await self.http.close()
        if self.db:await self.db.close()

    def destination(self, target=''):
        if self.settings.discord_bot_configured and not target.startswith('https://'):
            token = self.settings.discord_bot_token
            channel = target or self.settings.discord['channel_id']
            return (f'https://discord.com/api/v10/channels/{channel}/messages',
                    hashlib.sha256(('bot:' + channel + ':' + token).encode()).hexdigest(),
                    {'Authorization': 'Bot ' + token})
        raw = target or self.settings.discord_webhook
        if not raw: raise RuntimeError('Discord אינו מוגדר')
        url = webhook_url(raw)
        return url, hashlib.sha256(url.encode()).hexdigest(), {}

    async def deliver(self,text,buttons=None,*,event_id=None,force=False,target=''):
        if not self.settings.discord.get('enabled') and not force:raise RuntimeError('Discord כבוי')
        url, dest, headers = self.destination(target)
        await self.start()
        event_id=event_id or str(uuid.uuid4())
        async with self.lock:
            payloads = render_bot(text,buttons,self.settings.discord_bot_token) if headers else render(text,buttons,self.settings.browser_url)
            for i,payload in enumerate(payloads):
                label = (target or self.settings.discord.get('channel_id')) if headers else 'webhook:' + dest[:12]
                await self.db.execute('INSERT OR IGNORE INTO delivery(event_id,destination,part,payload,created,state,next_attempt,kind,target,health_notice) VALUES(?,?,?,?,?,?,?,?,?,?)',
                    (event_id,dest,i,json.dumps(payload,ensure_ascii=False),time.time(),'pending',time.time(),notification_kind.get(),label,int(health_notice.get())))
            await self.db.commit()
        await self.drain(event_id=event_id,force=force)
        cur=await self.db.execute('SELECT state FROM delivery WHERE event_id=?',(event_id,))
        states=[r['state'] for r in await cur.fetchall()]
        if any(s in ('failed','unknown') for s in states):raise DiscordDeliveryError('שליחת Discord נכשלה או שתוצאתה אינה ודאית; ראו יומן מערכת')
        if any(s == 'pending' for s in states) and self.audit and not health_notice.get():
            await self.audit('discord', label, notification_kind.get(), 'pending')
        return event_id  # pending means durably queued, not confirmed delivered.

    async def drain(self,event_id=None,force=False):
        async with self.lock:
            if not force and not self.settings.discord.get('enabled'):return
            if not self.settings.discord_bot_configured and not self.settings.discord_webhook:return
            destinations = {}
            for target in {''} | {r.get('target', '') for r in self.settings.discord.get('routes', {}).values()}:
                try:
                    url, dest, headers = self.destination(target)
                    destinations[dest] = (url, headers)
                except (ValueError, RuntimeError):
                    continue
            sql="SELECT * FROM delivery WHERE state='pending' AND next_attempt<=?"
            params=[time.time()]
            if event_id:sql+=' AND event_id=?';params.append(event_id)
            sql+=' ORDER BY created,part LIMIT 10'
            cur=await self.db.execute(sql,params)
            for row in await cur.fetchall():
                current = await (await self.db.execute('SELECT state FROM delivery WHERE event_id=? AND destination=? AND part=?', self.pk(row))).fetchone()
                if current['state'] != 'pending': continue
                if row['destination'] not in destinations:
                    await self.finish(row,'failed','destination_changed');continue
                url, headers = destinations[row['destination']]
                if row['created']<time.time()-3600:
                    await self.finish(row,'failed','expired');continue
                await self.db.execute("UPDATE delivery SET state='sending',attempts=attempts+1 WHERE event_id=? AND destination=? AND part=?", self.pk(row))
                await self.db.commit()
                if not self.http:self.http=aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=20,connect=5))
                try:
                    async with self.http.post(url,json=json.loads(row['payload']),headers=headers,allow_redirects=False) as response:
                        status=response.status
                        if status==200:
                            data=await response.json(); mid=data.get('id')
                            if not isinstance(mid,str) or not mid.isdigit():
                                await self.finish(row,'unknown','missing_message_id');continue
                            await self.finish(row,'sent',None,mid);continue
                        if status==429:
                            try:
                                data=await response.json(); delay=float(data.get('retry_after',response.headers.get('Retry-After',1)))
                            except (ValueError,TypeError,aiohttp.ContentTypeError):delay=5
                            await self.retry(row,max(1,delay) if math.isfinite(delay) else 5,'rate_limited');break
                        if status>=500:
                            await self.retry(row,2**(row['attempts']+1),'http_5xx');break
                        await self.finish(row,'failed',f'http_{status}')
                except aiohttp.ClientConnectorError:
                    await self.retry(row,2**(row['attempts']+1),'connect_failed');break
                except (asyncio.TimeoutError,aiohttp.ClientError,ValueError):
                    # Never print exceptions: they can contain the full webhook URL.
                    await self.finish(row,'unknown','delivery_uncertain')

    @staticmethod
    def pk(row):return (row['event_id'],row['destination'],row['part'])

    async def retry(self,row,delay,error):
        if row['attempts']>=2 or delay>3600:return await self.finish(row,'failed',error)
        await self.db.execute("UPDATE delivery SET state='pending',error=?,next_attempt=? WHERE event_id=? AND destination=? AND part=?",(error,time.time()+delay+random.random(),*self.pk(row)))
        await self.db.commit()

    async def finish(self,row,state,error,mid=None):
        await self.db.execute('UPDATE delivery SET state=?,error=?,message_id=?,payload=CASE WHEN ? IN (\'sent\',\'failed\',\'unknown\') THEN \'{}\' ELSE payload END WHERE event_id=? AND destination=? AND part=?',(state,error,mid,state,*self.pk(row)))
        await self.db.commit()
        if state == 'sent':
            await self.log('info', 'Discord אישר קבלת הודעה', f"event={row['event_id']} destination={row['destination'][:12]} message={mid}", channel='discord')
        if self.audit and not row['health_notice']:
            await self.audit('discord', row['target'], row['kind'], state, error)
        if state in ('failed','unknown'):
            await self.db.execute("UPDATE delivery SET state='failed',error='earlier_part_failed',payload='{}' WHERE event_id=? AND destination=? AND state='pending'",(row['event_id'],row['destination']))
            await self.db.commit()
            await self.log('error','שליחת Discord נכשלה' if state=='failed' else 'שליחת Discord לא אומתה — לא ננסה שוב כדי למנוע כפילות',f"event={row['event_id']} part={row['part']} status={error}",channel='discord')

    async def status(self):
        if not self.db:return {'queued':0,'failed':0,'unknown':0}
        cur=await self.db.execute('SELECT state,count(*) AS n FROM delivery GROUP BY state')
        counts={r['state']:r['n'] for r in await cur.fetchall()}
        return {'queued':counts.get('pending',0)+counts.get('sending',0),'failed':counts.get('failed',0),'unknown':counts.get('unknown',0)}

    async def worker(self):
        while True:
            await asyncio.sleep(5)
            try:await self.drain()
            except asyncio.CancelledError:raise
            except Exception:
                # Sanitized and bounded; no raw transport exception or response body.
                await self.log('error','תקלה בתור התראות Discord',channel='discord')
                await asyncio.sleep(30)
