'use strict';
const $=id=>document.getElementById(id);
const names={summary:'סיכום',sessions:'לוח אימונים',memberships:'כרטיסיות',automations:'אוטומציות',calendar:'יומן',history:'היסטוריה',reviews:'ביקורות',events:'יומן מערכת',status:'מצב מערכת',settings:'הגדרות',studio:'סטודיו',notifications:'התראות'};
const labels={next_class:'האימון הבא',next_7_days:'שבעת הימים הקרובים',booked:'רשומים',planned:'מתוכננים',standby:'בהמתנה',memberships:'כרטיסיות',name:'שם',date:'תאריך',start_time:'שעת התחלה',end_time:'סיום',category_name:'אימון',coach_name:'מדריך',sessions_left:'יתרה בכרטיסייה',available_after_planned:'פנוי אחרי תכנון',verification_state:'מצב אימות',attention:'דורש תשומת לב',waiting_for_sync:'ממתינים לסנכרון',action_required:'נדרשת פעולה',enabled:'פעיל',state:'מצב',coach_feedback:'דירוג מדריך',class_feedback:'דירוג אימון',ts:'זמן',source:'מקור',level:'חומרה',event_count:'מספר אירועים',last_sync:'עדכון אחרון',notifications:'התראות',google_calendar:'יומן Google',connected:'מחובר',automations:'אוטומציות',total:'סה״כ',has_more:'קיימים נתונים נוספים',scope:'תחום',reviews:'ביקורות',events:'אירועים',history:'היסטוריה',sessions:'אימונים'};
let key='',section='summary',pending=false,offset=0,cursor=0;
try{key=sessionStorage.getItem('arbox_view_key')||localStorage.getItem('arbox_api_key')||'';}catch(_){}
$('credential').value=key;
async function request(path,method='GET'){const r=await fetch(path,{method,headers:{'X-Api-Key':key},cache:'no-store'});if(!r.ok)throw Error(r.status===401?'המפתח חסר או אינו תקין':r.status===409?'אין סטודיו פעיל או שהסטודיו השתנה':'הנתונים אינם זמינים כרגע');return r.json();}
function render(value,host){if(value===null||typeof value!=='object'){host.textContent=value===null?'לא ידוע':typeof value==='boolean'?(value?'כן':'לא'):String(value);return;}if(Array.isArray(value)&&!value.length){host.textContent='אין נתונים';return;}for(const [k,v]of Object.entries(value)){const row=document.createElement('div');row.className=typeof v==='object'&&v!==null?'record':'pair';if(!Array.isArray(value)){const label=document.createElement('strong');label.textContent=labels[k]||k;row.append(label);}const cell=document.createElement(typeof v==='object'&&v!==null?'div':'span');render(v,cell);row.append(cell);host.append(row);}}
async function load(){if(!key||pending)return;pending=true;const active=section,credential=key;try{const d=await request('/api/view/'+active+'?offset='+offset+'&after_id='+cursor);if(active!==section||credential!==key)return;$('content').replaceChildren();render(d.data,$('content'));$('more').hidden=!d.data.has_more;$('more').onclick=()=>{if(pending)return;if(active==='events')cursor=d.data.next_after_id;else offset+=100;load();};$('freshness').textContent=(d.meta.stale?'⚠ מידע לא עדכני · ':'')+'עדכון מקור: '+(d.meta.last_sync||'טרם סונכרן')+' · '+d.meta.timezone;$('message').textContent='';}catch(e){$('content').replaceChildren();$('more').hidden=true;$('freshness').textContent='';$('message').textContent=e.message;}finally{pending=false;}}
for(const [id,name]of Object.entries(names)){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{if(pending)return;section=id;offset=0;cursor=0;for(const child of $('tabs').children)child.setAttribute('aria-current',String(child===b));load();};b.setAttribute('aria-current',String(id===section));$('tabs').append(b);}
$('connect').onclick=async()=>{key=$('credential').value.trim();try{sessionStorage.setItem('arbox_view_key',key);}catch(_){}await load();$('access').hidden=true;try{const d=await request('/api/view-access');$('access').hidden=false;$('keyState').textContent=d.enabled?'מפתח צפייה פעיל':'לא נוצר מפתח צפייה';}catch(_){}};
$('forget').onclick=()=>{$('more').hidden=true;key='';$('credential').value='';$('issued').value='';$('issued').hidden=true;$('copy').hidden=true;$('access').hidden=true;$('content').replaceChildren();$('freshness').textContent='';try{sessionStorage.removeItem('arbox_view_key');}catch(_){}};
$('rotate').onclick=async()=>{if(!confirm('ליצור מפתח צפייה חדש? המפתח הקודם יפסיק לעבוד.'))return;try{const d=await request('/api/view-access','POST');$('issued').value=d.key;$('issued').hidden=false;$('copy').hidden=false;$('keyState').textContent='נוצר מפתח חדש. שמרו אותו עכשיו; הוא לא יוצג שוב.';}catch(e){$('message').textContent=e.message;}};
$('revoke').onclick=async()=>{if(!confirm('לבטל את מפתח הצפייה? שילובים שמשתמשים בו יפסיקו לקבל נתונים.'))return;try{await request('/api/view-access','DELETE');$('issued').value='';$('issued').hidden=true;$('copy').hidden=true;$('keyState').textContent='מפתח הצפייה בוטל';}catch(e){$('message').textContent=e.message;}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('issued').value);$('keyState').textContent='המפתח הועתק';}catch(_){$('issued').type='text';$('issued').select();$('keyState').textContent='העתיקו את המפתח המסומן';}};
setInterval(()=>{if(!document.hidden)load();},60000);if(key)$('connect').click();
